// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CostaFascinosa.Data;

public partial class Actividade
{
    public int IdActividad { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int? IdCategoria { get; set; }

    public string Duracion { get; set; }

    public int? IdTurno { get; set; }

    public int? IdDestinatario { get; set; }

    public int? IdCoordinador { get; set; }

    public int? IdCodVestimenta { get; set; }

    public int? IdZona { get; set; }

    public int? CupoMax { get; set; }

    public byte[] RequiereReserva { get; set; }

    public decimal? Costo { get; set; }

    public virtual Categoria IdCategoriaNavigation { get; set; }

    public virtual CodVestimenta IdCodVestimentaNavigation { get; set; }

    public virtual Coordinadore IdCoordinadorNavigation { get; set; }

    public virtual Destinatario IdDestinatarioNavigation { get; set; }

    public virtual Turno IdTurnoNavigation { get; set; }

    public virtual Zona IdZonaNavigation { get; set; }

    public virtual ICollection<ResenasActividade> ResenasActividades { get; set; } = new List<ResenasActividade>();

    public virtual ICollection<ReservasActividade> ReservasActividades { get; set; } = new List<ReservasActividade>();
}