// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CostaFascinosa.Data;

public partial class Amenity
{
    public int IdAmenitie { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int? IdCategoria { get; set; }

    public int? IdTurno { get; set; }

    public int? IdDestinatario { get; set; }

    public int? IdCodVestimenta { get; set; }

    public int? IdZona { get; set; }

    public virtual Categoria IdCategoriaNavigation { get; set; }

    public virtual CodVestimenta IdCodVestimentaNavigation { get; set; }

    public virtual Destinatario IdDestinatarioNavigation { get; set; }

    public virtual Turno IdTurnoNavigation { get; set; }

    public virtual Zona IdZonaNavigation { get; set; }

    public virtual ICollection<ResenasAmenity> ResenasAmenities { get; set; } = new List<ResenasAmenity>();
}