// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CostaFascinosa.Data;

public partial class ConsumosGastronomico
{
    public int IdConsumoGastronomico { get; set; }

    public int? IdConsumo { get; set; }

    public int? IdProducto { get; set; }

    public int? Cantidad { get; set; } = 1;

    public decimal? Precio { get; set; }
    [JsonIgnore]
    public virtual ConsumosHabitacione IdConsumoNavigation { get; set; }

    public virtual ProductosGastronomico IdProductoNavigation { get; set; }
}