// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CostaFascinosa.Data;

public partial class ConsumosHabitacione
{
    public int IdConsumo { get; set; }

    public int? NroHabitacion { get; set; }

    public int? IdUsuario { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual ICollection<ConsumosGastronomico> ConsumosGastronomicos { get; set; } = new List<ConsumosGastronomico>();

    public virtual Usuario IdUsuarioNavigation { get; set; }

    public virtual Habitacione NroHabitacionNavigation { get; set; }

    public virtual ICollection<ReservasActividade> ReservasActividades { get; set; } = new List<ReservasActividade>();
}