// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CostaFascinosa.Data;

public partial class Coordinadore
{
    public int IdCoordinador { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public DateTime? FechaNac { get; set; }

    public int? Nacionalidad { get; set; }
    
    [JsonIgnore]
    public virtual ICollection<Actividade> Actividades { get; set; } = new List<Actividade>();

    public virtual Nacionalidade NacionalidadNavigation { get; set; }
}