// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CostaFascinosa.Data;

public partial class Habitacione
{
    public int NroHabitacion { get; set; }

    public string Descripcion { get; set; }

    public int? IdTipoHabitacion { get; set; }

    public int? IdZona { get; set; }

    public virtual ICollection<ConsumosHabitacione> ConsumosHabitaciones { get; set; } = new List<ConsumosHabitacione>();

    public virtual TiposHabitacione IdTipoHabitacionNavigation { get; set; }

    public virtual Zona IdZonaNavigation { get; set; }

    public virtual ICollection<Pasajero> Pasajeros { get; set; } = new List<Pasajero>();
}