// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CostaFascinosa.Data;

public partial class Pasajero
{
    public int IdPasajero { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int? IdTipoDocumento { get; set; }

    public int? NroDocumento { get; set; }

    public int? Nacionalidad { get; set; }

    public DateTime? FechaNac { get; set; }

    public string Sexo { get; set; }

    public DateTime? FechaAbordo { get; set; }

    public DateTime? FechaDesbordo { get; set; }

    public int? IdEstado { get; set; }

    public int? NroHabitacion { get; set; }

    [JsonIgnore]
    public virtual ICollection<Contacto> Contactos { get; set; } = new List<Contacto>();

    public virtual Estado IdEstadoNavigation { get; set; }

    public virtual TiposDocumento IdTipoDocumentoNavigation { get; set; }

    public virtual Nacionalidade NacionalidadNavigation { get; set; }

    public virtual Habitacione NroHabitacionNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}