// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CostaFascinosa.Data;

public partial class ProductosGastronomico
{
    public int IdProducto { get; set; }

    public int? IdServicio { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int? IdTipoProducto { get; set; }

    public decimal? Precio { get; set; }
    [JsonIgnore]
    public virtual ICollection<ConsumosGastronomico> ConsumosGastronomicos { get; set; } = new List<ConsumosGastronomico>();

    public virtual ServiciosGastronomico IdServicioNavigation { get; set; }

    public virtual TiposProducto IdTipoProductoNavigation { get; set; }
}