// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CostaFascinosa.Data;

public partial class ResenasActividade
{
    public int IdResenaAct { get; set; }

    public string Comentario { get; set; }

    public int? Puntuacion { get; set; }

    public int? IdActividad { get; set; }

    public int? IdUsuario { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual Actividade IdActividadNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}