// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CostaFascinosa.Data;

public partial class ResenasAmenity
{
    public int IdResenaAmenitie { get; set; }

    public string Comentario { get; set; }

    public int? Puntuacion { get; set; }

    public int? IdAmenitie { get; set; }

    public int? IdUsuario { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual Amenity IdAmenitieNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}