// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CostaFascinosa.Data;

public partial class TiposHabitacione
{
    public int IdTipoHabitacion { get; set; }

    public string Tipo { get; set; }
    [JsonIgnore]
    public virtual ICollection<Habitacione> Habitaciones { get; set; } = new List<Habitacione>();
}