// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace CostaFascinosa.Data;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string Nombre { get; set; }
   
    public int? Contraseña { get; set; }

    //public string PasswordHash { get; set; }

    public int? IdPasajero { get; set; }
    [JsonIgnore]
    public virtual ICollection<ConsumosHabitacione> ConsumosHabitaciones { get; set; } = new List<ConsumosHabitacione>();

    public virtual Pasajero IdPasajeroNavigation { get; set; }

    [JsonIgnore]
    public virtual ICollection<ResenasActividade> ResenasActividades { get; set; } = new List<ResenasActividade>();
    [JsonIgnore]
    public virtual ICollection<ResenasAmenity> ResenasAmenities { get; set; } = new List<ResenasAmenity>();
    [JsonIgnore]
    public virtual ICollection<ResenasServicio> ResenasServicios { get; set; } = new List<ResenasServicio>();
    [JsonIgnore]
    public virtual ICollection<ReservasServicio> ReservasServicios { get; set; } = new List<ReservasServicio>();
}