// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CostaFascinosa.Data;

public partial class Zona
{
    public int IdZona { get; set; }

    public string Descripcion { get; set; }

    public int? Piso { get; set; }
    [JsonIgnore]
    public virtual ICollection<Actividade> Actividades { get; set; } = new List<Actividade>();
    [JsonIgnore]
    public virtual ICollection<Amenity> Amenities { get; set; } = new List<Amenity>();
    [JsonIgnore]
    public virtual ICollection<Habitacione> Habitaciones { get; set; } = new List<Habitacione>();
    [JsonIgnore]
    public virtual ICollection<ServiciosGastronomico> ServiciosGastronomicos { get; set; } = new List<ServiciosGastronomico>();
}